version: '3.8'

services:
  fastapi:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  streamlit:
    build: ./webapp
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - PORT=8501
